//for get Price Title actions
export const REQUEST_FOR_GET_PLAN_IS_IN_PROGRESS = 'REQUEST_FOR_GET_PLAN_IS_IN_PROGRESS';
export const REQUEST_FOR_GET_PLAN_SUCCESS = 'REQUEST_FOR_GET_PLAN_SUCCESS';
export const REQUEST_FOR_GET_PLAN_ERROR = 'REQUEST_FOR_GET_PLAN_ERROR';

//for post Price Title actions
export const REQUEST_FOR_ADD_PLAN_IS_IN_PROGRESS = 'REQUEST_FOR_ADD_PLAN_IS_IN_PROGRESS';
export const REQUEST_FOR_ADD_PLAN_SUCCESS = 'REQUEST_FOR_ADD_PLAN_SUCCESS';
export const REQUEST_FOR_ADD_PLAN_ERROR = 'REQUEST_FOR_ADD_PLAN_ERROR';

//for patch (Update) Price Title actions
export const REQUEST_FOR_UPDATE_PLAN_IS_IN_PROGRESS = 'REQUEST_FOR_UPDATE_PLAN_IS_IN_PROGRESS';
export const REQUEST_FOR_UPDATE_PLAN_SUCCESS = 'REQUEST_FOR_UPDATE_PLAN_SUCCESS';
export const REQUEST_FOR_UPDATE_PLAN_ERROR = 'REQUEST_FOR_UPDATE_PLAN_ERROR';

//for Delete Price Title actions
export const REQUEST_FOR_DELETE_PLAN_IS_IN_PROGRESS = 'REQUEST_FOR_DELETE_PLAN_IS_IN_PROGRESS';
export const REQUEST_FOR_DELETE_PLAN_SUCCESS = 'REQUEST_FOR_DELETE_PLAN_SUCCESS';
export const REQUEST_FOR_DELETE_PLAN_ERROR = 'REQUEST_FOR_DELETE_PLAN_ERROR';