//for get mainSpecs actions
export const REQUEST_FOR_GET_MAINSPECS_IS_IN_PROGRESS = 'REQUEST_FOR_GET_MAINSPECS_IS_IN_PROGRESS';
export const REQUEST_FOR_GET_MAINSPECS_SUCCESS = 'REQUEST_FOR_GET_MAINSPECS_SUCCESS';
export const REQUEST_FOR_GET_MAINSPECS_ERROR = 'REQUEST_FOR_GET_MAINSPECS_ERROR';

//for post mainSpecs actions
export const REQUEST_FOR_ADD_MAINSPECS_IS_IN_PROGRESS = 'REQUEST_FOR_ADD_MAINSPECS_IS_IN_PROGRESS';
export const REQUEST_FOR_ADD_MAINSPECS_SUCCESS = 'REQUEST_FOR_ADD_MAINSPECS_SUCCESS';
export const REQUEST_FOR_ADD_MAINSPECS_ERROR = 'REQUEST_FOR_ADD_MAINSPECS_ERROR';
export const REQUEST_FOR_ADD_MAINSPECS_DUPLICATE = 'REQUEST_FOR_ADD_MAINSPECS_DUPLICATE';

//for patch (Update) mainTypes actions
export const REQUEST_FOR_UPDATE_MAINSPECS_IS_IN_PROGRESS = 'REQUEST_FOR_UPDATE_MAINSPECS_IS_IN_PROGRESS';
export const REQUEST_FOR_UPDATE_MAINSPECS_SUCCESS = 'REQUEST_FOR_UPDATE_MAINSPECS_SUCCESS';
export const REQUEST_FOR_UPDATE_MAINSPECS_ERROR = 'REQUEST_FOR_UPDATE_MAINSPECS_ERROR';

//for Delete mainSpecs actions
export const REQUEST_FOR_DELETE_MAINSPECS_IS_IN_PROGRESS = 'REQUEST_FOR_DELETE_MAINSPECS_IS_IN_PROGRESS';
export const REQUEST_FOR_DELETE_MAINSPECS_SUCCESS = 'REQUEST_FOR_DELETE_MAINSPECS_SUCCESS';
export const REQUEST_FOR_DELETE_MAINSPECS_ERROR = 'REQUEST_FOR_DELETE_MAINSPECS_ERROR';
export const REQUEST_FOR_DELETE_MAINSPECS_AVAILABLE = 'REQUEST_FOR_DELETE_MAINSPECS_AVAILABLE';