//for get Price Title actions
export const REQUEST_FOR_GET_PRICE_TITLE_IS_IN_PROGRESS = 'REQUEST_FOR_GET_PRICE_TITLE_IS_IN_PROGRESS';
export const REQUEST_FOR_GET_PRICE_TITLE_SUCCESS = 'REQUEST_FOR_GET_PRICE_TITLE_SUCCESS';
export const REQUEST_FOR_GET_PRICE_TITLE_ERROR = 'REQUEST_FOR_GET_PRICE_TITLE_ERROR';

//for post Price Title actions
export const REQUEST_FOR_ADD_PRICE_TITLE_IS_IN_PROGRESS = 'REQUEST_FOR_ADD_PRICE_TITLE_IS_IN_PROGRESS';
export const REQUEST_FOR_ADD_PRICE_TITLE_SUCCESS = 'REQUEST_FOR_ADD_PRICE_TITLE_SUCCESS';
export const REQUEST_FOR_ADD_PRICE_TITLE_ERROR = 'REQUEST_FOR_ADD_PRICE_TITLE_ERROR';

//for patch (Update) Price Title actions
export const REQUEST_FOR_UPDATE_PRICE_TITLE_IS_IN_PROGRESS = 'REQUEST_FOR_UPDATE_PRICE_TITLE_IS_IN_PROGRESS';
export const REQUEST_FOR_UPDATE_PRICE_TITLE_SUCCESS = 'REQUEST_FOR_UPDATE_PRICE_TITLE_SUCCESS';
export const REQUEST_FOR_UPDATE_PRICE_TITLE_ERROR = 'REQUEST_FOR_UPDATE_PRICE_TITLE_ERROR';

//for Delete Price Title actions
export const REQUEST_FOR_DELETE_PRICE_TITLE_IS_IN_PROGRESS = 'REQUEST_FOR_DELETE_PRICE_TITLE_IS_IN_PROGRESS';
export const REQUEST_FOR_DELETE_PRICE_TITLE_SUCCESS = 'REQUEST_FOR_DELETE_PRICE_TITLE_SUCCESS';
export const REQUEST_FOR_DELETE_PRICE_TITLE_ERROR = 'REQUEST_FOR_DELETE_PRICE_TITLE_ERROR';