//for get Price VALUE actions
export const REQUEST_FOR_GET_PRICE_VALUE_IS_IN_PROGRESS = 'REQUEST_FOR_GET_PRICE_VALUE_IS_IN_PROGRESS';
export const REQUEST_FOR_GET_PRICE_VALUE_SUCCESS = 'REQUEST_FOR_GET_PRICE_VALUE_SUCCESS';
export const REQUEST_FOR_GET_PRICE_VALUE_ERROR = 'REQUEST_FOR_GET_PRICE_VALUE_ERROR';

//for post Price VALUE actions
export const REQUEST_FOR_ADD_PRICE_VALUE_IS_IN_PROGRESS = 'REQUEST_FOR_ADD_PRICE_VALUE_IS_IN_PROGRESS';
export const REQUEST_FOR_ADD_PRICE_VALUE_SUCCESS = 'REQUEST_FOR_ADD_PRICE_VALUE_SUCCESS';
export const REQUEST_FOR_ADD_PRICE_VALUE_ERROR = 'REQUEST_FOR_ADD_PRICE_VALUE_ERROR';

//for patch (Update) Price VALUE actions
export const REQUEST_FOR_UPDATE_PRICE_VALUE_IS_IN_PROGRESS = 'REQUEST_FOR_UPDATE_PRICE_VALUE_IS_IN_PROGRESS';
export const REQUEST_FOR_UPDATE_PRICE_VALUE_SUCCESS = 'REQUEST_FOR_UPDATE_PRICE_VALUE_SUCCESS';
export const REQUEST_FOR_UPDATE_PRICE_VALUE_ERROR = 'REQUEST_FOR_UPDATE_PRICE_VALUE_ERROR';

//for Delete Price VALUE actions
export const REQUEST_FOR_DELETE_PRICE_VALUE_IS_IN_PROGRESS = 'REQUEST_FOR_DELETE_PRICE_VALUE_IS_IN_PROGRESS';
export const REQUEST_FOR_DELETE_PRICE_VALUE_SUCCESS = 'REQUEST_FOR_DELETE_PRICE_VALUE_SUCCESS';
export const REQUEST_FOR_DELETE_PRICE_VALUE_ERROR = 'REQUEST_FOR_DELETE_PRICE_VALUE_ERROR';