//for get Sub actions
export const REQUEST_FOR_GET_SUBTYPE_IS_IN_PROGRESS = 'REQUEST_FOR_GET_SUBTYPE_IS_IN_PROGRESS';
export const REQUEST_FOR_GET_SUBTYPE_SUCCESS = 'REQUEST_FOR_GET_SUBTYPE_SUCCESS';
export const REQUEST_FOR_GET_SUBTYPE_ERROR = 'REQUEST_FOR_GET_SUBTYPE_ERROR';

//for post Sub actions
export const REQUEST_FOR_ADD_SUBTYPE_IS_IN_PROGRESS = 'REQUEST_FOR_ADD_SUBTYPE_IS_IN_PROGRESS';
export const REQUEST_FOR_ADD_SUBTYPE_SUCCESS = 'REQUEST_FOR_ADD_SUBTYPE_SUCCESS';
export const REQUEST_FOR_ADD_SUBTYPE_ERROR = 'REQUEST_FOR_ADD_SUBTYPE_ERROR';

//for patch (Update) subtype actions
export const REQUEST_FOR_UPDATE_SUBTYPE_IS_IN_PROGRESS = 'REQUEST_FOR_UPDATE_SUBTYPE_IS_IN_PROGRESS';
export const REQUEST_FOR_UPDATE_SUBTYPE_SUCCESS = 'REQUEST_FOR_UPDATE_SUBTYPE_SUCCESS';
export const REQUEST_FOR_UPDATE_SUBTYPE_ERROR = 'REQUEST_FOR_UPDATE_SUBTYPE_ERROR';

//for Delete subTypes actions
export const REQUEST_FOR_DELETE_SUBTYPE_IS_IN_PROGRESS = 'REQUEST_FOR_DELETE_SUBTYPE_IS_IN_PROGRESS';
export const REQUEST_FOR_DELETE_SUBTYPE_SUCCESS = 'REQUEST_FOR_DELETE_SUBTYPE_SUCCESS';
export const REQUEST_FOR_DELETE_SUBTYPE_ERROR = 'REQUEST_FOR_DELETE_SUBTYPE_ERROR';