//for get mainSpecs actions
export const REQUEST_FOR_GET_SUBSPECS_IS_IN_PROGRESS = 'REQUEST_FOR_GET_SUBSPECS_IS_IN_PROGRESS';
export const REQUEST_FOR_GET_SUBSPECS_SUCCESS = 'REQUEST_FOR_GET_SUBSPECS_SUCCESS';
export const REQUEST_FOR_GET_SUBSPECS_ERROR = 'REQUEST_FOR_GET_SUBSPECS_ERROR';

//for post mainSpecs actions
export const REQUEST_FOR_ADD_SUBSPECS_IS_IN_PROGRESS = 'REQUEST_FOR_ADD_SUBSPECS_IS_IN_PROGRESS';
export const REQUEST_FOR_ADD_SUBSPECS_SUCCESS = 'REQUEST_FOR_ADD_SUBSPECS_SUCCESS';
export const REQUEST_FOR_ADD_SUBSPECS_ERROR = 'REQUEST_FOR_ADD_SUBSPECS_ERROR';
export const REQUEST_FOR_ADD_SUBSPECS_DUPLICATE = 'REQUEST_FOR_ADD_SUBSPECS_DUPLICATE';

//for patch (Update) mainTypes actions
export const REQUEST_FOR_UPDATE_SUBSPECS_IS_IN_PROGRESS = 'REQUEST_FOR_UPDATE_SUBSPECS_IS_IN_PROGRESS';
export const REQUEST_FOR_UPDATE_SUBSPECS_SUCCESS = 'REQUEST_FOR_UPDATE_SUBSPECS_SUCCESS';
export const REQUEST_FOR_UPDATE_SUBSPECS_ERROR = 'REQUEST_FOR_UPDATE_SUBSPECS_ERROR';

//for Delete mainSpecs actions
export const REQUEST_FOR_DELETE_SUBSPECS_IS_IN_PROGRESS = 'REQUEST_FOR_DELETE_SUBSPECS_IS_IN_PROGRESS';
export const REQUEST_FOR_DELETE_SUBSPECS_SUCCESS = 'REQUEST_FOR_DELETE_SUBSPECS_SUCCESS';
export const REQUEST_FOR_DELETE_SUBSPECS_ERROR = 'REQUEST_FOR_DELETE_SUBSPECS_ERROR';
export const REQUEST_FOR_DELETE_SUBSPECS_AVAILABLE = 'REQUEST_FOR_DELETE_SUBSPECS_AVAILABLE';