// GET student Activity
export const REQ_FOR_LOGIN_PROGRESS_CUSTOMER = "REQ_FOR_LOGIN_PROGRESS_CUSTOMER"
export const REQ_FOR_LOGIN_SUCCESS_CUSTOMER = "REQ_FOR_LOGIN_SUCCESS_CUSTOMER"
export const REQ_FOR_LOGIN_ERROR_CUSTOMER = "REQ_FOR_LOGIN_ERROR_CUSTOMER"
export const REQ_FOR_LOGIN_FAILED_CUSTOMER = "REQ_FOR_LOGIN_FAILED_CUSTOMER"